apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: YOUR-DOCKERHUB-USERNAME/1-tier-app-deployment:v1  # 👈 Update to v2 later
        ports:
        - containerPort: 5000